### ISSUE TITLE
Aparência geral do site

### ISSUE THREAD

**Issue by Almendary** [TaturanaMobi/plataforma-v2#1]

**Comment by Almendary** [comment]
- carrossel da home: desconfigurado, e cartazes não correspondem às sinopses
- instabilidade dos gráficos e outras infos nas páginas dos filmes (UFs não aparecem, gráficos são móveis)
- nova página: quem somos e portfolio

**Comment by lpirola** [comment]
Estamos organizando em https://www.pivotaltracker.com/n/projects/2191794
